language: python
python:
  - "3.6"

env:
  - DJANGO_VERSION=1.11.5

# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
# command to run tests
script:
  #- pytest # or py.test for Python versions 3.5 and below
  - python WebApp_One/manage.py test WebApp_One/
